# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0002_auto_20170913_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='userID',
            new_name='appID',
        ),
        migrations.AddField(
            model_name='board',
            name='appID',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='gameID',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='board',
            name='data',
            field=models.CharField(default='', max_length=500),
        ),
    ]
