# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0005_queue_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.CharField(default='', max_length=30),
        ),
    ]
