# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0010_remove_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='data',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
