# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0011_auto_20170918_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='data',
            field=models.CharField(default='{}', max_length=500),
        ),
    ]
