# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0012_auto_20170918_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shipsLeft',
            field=models.IntegerField(default=6),
        ),
    ]
