# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0013_board_shipsleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
