# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleship', '0014_board_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ships',
            field=models.CharField(default='{}', max_length=500),
        ),
    ]
